### ISSUE TITLE
Last updated 153 days ago

### ISSUE THREAD

**Issue by Asuza** [aslushnikov/ispuppeteerfirefoxready#3]
The README file says that this information updates every 5 minutes, but the website says it was last updated 153 days ago. @aslushnikov has something gone awry, or am I misunderstanding how this works?

**Comment by aslushnikov** [comment]
> The README file says that this information updates every 5 minutes, but the website says it was last updated 153 days ago

Yeah this is accurate. I don't think puppeteer-firefox has been updated during last 6 months.

>  has something gone awry, or am I misunderstanding how this works?

The work and all the effort has moved over to https://github.com/microsoft/playwright
There's `playwright-firefox` if you care only about firefox.

Hope this helps!
