### ISSUE TITLE
Test sur isn't synchronising anymore

### ISSUE THREAD

**Issue by ylecuyer** [aslushnikov/ispuppeteerfirefoxready#4]
Hi

It looks like the test suite hasn't been updated for a while now (6 months) whereas the readme says it should be updated now often. 

Could you please update the test suite?

Thanks

**Comment by aslushnikov** [comment]
Hi!

`puppeteer-firefox` is [not maintained](https://github.com/puppeteer/puppeteer/issues/5397) anymore and got a new life as part of the [`playwright`](https://github.com/microsoft/playwright) project.

For a similar table on browser support, playwright has [Is Playwright ready?](https://aslushnikov.github.io/isplaywrightready/) page.
